### ISSUE TITLE
Remove sliding images and make problem tracks as squares

### ISSUE THREAD

**Issue by ChiragJS** [IEEE-RVCE/hack-it-right#45]
Remove the Carousel under Hackathon Tracks 
Make card for each hackathon track and Add the list of problem statements to it

**Comment by ChiragJS** [comment]
Generative AI 4 Soc
Empower positive change with AI. From personalized healthcare to inclusive education, explore how AI can transform society for the better.


Blockchain 4 Soc
Unleash the potential of Blockchain for societal good. Revolutionize supply chains, enhance identity security, and create transparent solutions for humanitarian aid.


Fintech 4 Soc
Shape a better world with Fintech. Drive financial inclusion, support micro-entrepreneurs, and enable sustainable investments to make a lasting impact on communities



Add this content, remove the carousel , make seperate card for these

**Comment by ChiragJS** [comment]
@Tejas-R-Pattar

**Comment by ChiragJS** [comment]
still waiting for a pr on this issue @Tejas-R-Pattar

**Comment by ChiragJS** [comment]
@AyushRatan1 you can take this up if you want

**Comment by AyushRatan1** [comment]
@ChiragJS okay I will work on that
