### ISSUE TITLE
Remove and Add social media handles

### ISSUE THREAD

**Issue by ChiragJS** [IEEE-RVCE/hack-it-right#46]
In the landing page and footer section add and remove these:-
1.  remove dev and twitter icon remove discord and add gmail icon 
2. Linked In  link should head to IEEE-CompSoc linked in account and the instagram should head to IEEE-RVCE page

**Comment by Prajwalprakash3722** [comment]
@ChiragJS Main Execom has banned us to use IEEE Comp-Soc LinkedIn account, better to clarify once

**Comment by ChiragJS** [comment]
Yes , I dmed them

**Comment by SundarakrishnanN** [comment]
changes are down,please clarify on the usage of compsoc linkedin

**Comment by ChiragJS** [comment]
yea sure keep it on hold for now and push the changes , mention fixes #issuenumber on your pr
