### ISSUE TITLE
Align the footer area

### ISSUE THREAD

**Issue by ChiragJS** [IEEE-RVCE/hack-it-right#50]
The compsoc logo is in a different row Add all the three elements in the same row and see if it looks well aligned , show the results and based on that a decision will be made

**Comment by Prajwalprakash3722** [comment]
![image](https://github.com/IEEE-RVCE/hack-it-right/assets/71436720/a219c922-3877-47a6-a8f4-1be443fda529)

what is wrong with footer, I see its properly aligned?

**Comment by ChiragJS** [comment]
That's what I told them , they want it in the same row, it seems
